### ISSUE TITLE
Test portal and clearinghouse email

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/aws-transition#7]
The portal and clearinghouse send email under a variety of circumstances.

* Check the configuration files to verify that the correct addresses are in place
* Test portal email
** Request project lead privilege
** Request to be added to a project
* Test clearinghouse email
** Find some use cases...

**Comment by tcmitchell** [comment]
@hussamnasir reports:

**Portal** : I noticed that there was not much here. Just 4 emails , two
of which were addressed to my personal email that bounced because our
mailserver reject it as bogus domain. and the other two were the cronjob
errors i sent you earlier.

**CH** : I did not see any mail on the AWS CH server, so looked at the
mail log. I noticed that all email was being delivered to the either
root@geni.net or sent to geni users from ch-admins@geni.net . I dont see
any failures here, so its more like the AWS site is spoofing the
geni.net domain

**Comment by hussamnasir** [comment]
So if we would like to keep the email stuff as is, we need to know who is processing the current email being generated. Does BBN run an email server for the geni.net domain ?

**Comment by tcmitchell** [comment]
Email from the portal is currently sent from `www-data.gpolab.bbn.com`. The string that can accompany an email address is used to designate the experimenter who took the action that caused the mail to be sent.

Here's an example, where Alice Experimenter (alice@example.com) invites Bob Collaborator (bob@example.com) to join her project.

````
From: "Alice Experimenter (via the GENI Portal)" <www-data@gpolab.bbn.com>
To: bob@example.com
Reply-To: alice@example.com
````

This email then transitions from the portal host (nye.gpolab.bbn.com) to smtp.gpolab.bbn.com to mail.geni.net before being sent to the mail server at example.com (Bob's domain). Headers would look something like this, I think:

````
Received: from mail.geni.net by smtp.example.com
Received: from smtp.gpolab.bbn.com by mail.geni.net
Received: from nye.gpolab.bbn.com by smtp.gpolab.bbn.com
Received: by nye.gpolab.bbn.com
````

**Comment by tcmitchell** [comment]
We need to designate a new "from" address for the portal to use, either for the short term or for the long term. One idea is something like `no-reply@geni.net`. To do that we'd need to configure both the portal and clearinghouse hosts on AWS to send mail via mail.geni.net AND configure mail.geni.net to accept mail from these hosts AND possibly add the AWS hosts to DNS either in SPF or MX records.

(I'm out of my league here, so some of that might not make sense. Please correct it if you can.)

**Comment by hussamnasir** [comment]
I second this plan. This is absolutely what i had intended.  But then there is a second step that needs to be thought through. Whats happens to mail.geni.net/smtp.gpolab.bbn.com ? Do we need a new mail server ?

**Comment by tcmitchell** [comment]
As I understand it from a conversation with Heidi last week, smtp.gpolab.bbn.com will be going away, but mail.geni.net is expected to be transitioned to someone. We should clarify that. If mail.geni.net is also expected to go away, the portal would need to be configured to use some other domain altogether.

There's still [the issue of making the from address configurable](https://github.com/GENI-NSF/geni-portal/issues/1769). But that's something I know how to fix.

**Comment by tcmitchell** [comment]
We may need to have the hosts configured to send mail via mail.geni.net. Once the MX records go live, we'll have to see if it just works, or if the local mailer needs to be configured to send via mail.geni.net.

**Comment by hussamnasir** [comment]
A correction to the email issue code

  $headers  = "Reply-To: $email\r\n";
  $headers .= "From: \"$name (via the GENI Portal)\" <$portal_from_email>\r\n";
  $headers .= "Content-Type: text/plain; charset=UTF-8\r\n";
  $headers .= "Content-Transfer-Encoding: 8bit";

  mail($to,
       "Join my GENI project $project_name!",
       $message,
       $headers,
       "-f $portal_from_email");  // was $email originally
// This tells sendmail directly to resend the envelope-sender, so the portal users gets bounces

Your comment about the bounce will not work even if you use the GENI User's email address in most cases. That is exactly what an SPF spammer does to spoof emails.  
The case i ran across was special but most likely what will happen since project leaders and its members belong to the same institution. Our domain does an SPF check for every email incomming. SO if portalAWS says it is nasir@netlab.uky.edu and tries to invite somejunk@netlab.uky.edu, the mail will be rejected by our mail server assuming that someone is spoofing my email address to send mail when the only authrized server for netlab domain is ours and not portal AWS/mail.geni.net

So  lets not break our heads trying to figure out the mail bounce issue. Let just work on preventing portalAWS from spoofing other email address which is what the code above addresses.

**Comment by hussamnasir** [comment]
Plus  I am not a 100% sure it resolves the issue of mail spoofing nor does it address the issue (email bounce in case invited user does not exist) which you mentioned as the reason for using the geni user's email address in the from. I tried registering a non-existent user but  never received a bounce.  
I dont think this is wrong. There can be other behaviors, but i guess we should not break our heads trying to figure this out.
To address the spoofing issue we will need to replace the $email with $portal_from_email in both places and leave the $reply_to with the geni Project leader's email address. I tested this and it worked.

**Comment by tcmitchell** [comment]
I think we should try to remove the `-f $some_email` altogether. It was added to cause bounces to go to the experimenter so they'd know if they mistyped an email address. I don't recall the details, however. From what you're saying, it sounds like making the experimenter be the "envelope sender" triggers SPF blocking. And I don't think there's any point in setting the "envelope sender" to the from address (`$portal_from_email`), wouldn't that be the default?

Can you try without the `-f` flag by eliminating that argument? If that makes things better we can include it in the next release.

**Comment by tcmitchell** [comment]
Removing the `-f $some_email` does not work. The envelope sender does not default to the value of the From header. It defaults to the current user executing the code, which in this case is the web server user.

Following Hussam's example above is the winner. Setting both From and envelope sender to the configured address `$portal_from_email` is the best alternative. This allows email to get through SPF filters.
